### ISSUE TITLE
🛑 ICO Staging is down

### ISSUE THREAD

**Issue by steviewanders** [HakaiInstitute/upptime-trial#110]
In [`5745b54`](https://github.com/HakaiInstitute/upptime-trial/commit/5745b5422ea611b6e13982d3869180ac352982bc
), ICO Staging (https://test-ico.hakai.org/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by steviewanders** [comment]
@jeremyhakai @Mbrownshoes did somebody touch DNS or certs involving this today?

**Comment by jeremyhakai** [comment]
That was me. Just switched from old ico to new ico.


--
Jeremy Latham
Communications & Web Development

Tula Foundation / tula.org
Hakai Institute / hakai.org
C: 250-204-6373

**Comment by steviewanders** [comment]
Sweet, thanks for explaining
--
Steve Vandervalk
Hakai Institute

**Comment by jeremyhakai** [comment]
I turned deleted the test-ico dns entry, as I don't have a staging
environment setup for that. If we need one, I can make one, but it's a
single page and is done.

--
Jeremy Latham
Communications & Web Development

Tula Foundation / tula.org
Hakai Institute / hakai.org
C: 250-204-6373

**Comment by steviewanders** [comment]
Cool, will drop those URLS
